apiVersion: batch/v1
kind: Job
metadata:
  name: liquibase-job
spec:
  template:
    spec:
      initContainers:                    # <-- (1) Start here
      - name: create-db
        image: mysql:8.0                  # <-- (use mysql client image)
        command:
          - sh
          - -c
          - |
            mysql -h mysql-service -P 27018 -u root -proot -e "CREATE DATABASE IF NOT EXISTS dept_db;"
        env:
          - name: MYSQL_PWD
            value: root
      containers:
      - name: liquibase
        image: nikhil575/liquibase-with-mysql-driver:latest
        command:
          - "liquibase"
          - "--driver=com.mysql.cj.jdbc.Driver"
          - "--url=jdbc:mysql://dept-mysql-service:27018/dept_db"
          - "--username=root"
          - "--password=root"
          - "--changeLogFile=changelog.xml"
          - "--searchPath=/liquibase/changelog/"
          - "update"
        env:
          - name: DB_HOST
            value: "dept-mysql-service"
          - name: DB_PORT
            value: "27018"
          - name: DB_NAME
            value: "dept_db"
          - name: DB_USERNAME
            value: "root"
          - name: DB_PASSWORD
            value: "root"
      restartPolicy: OnFailure
  backoffLimit: 4